# Generated by Django 4.2.3 on 2023-07-09 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=6)),
                ('typology', models.CharField(max_length=100)),
                ('search_range', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotifiedAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=100, unique=True)),
                ('search_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.searchfilter')),
            ],
        ),
    ]
